// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMjUR6s_yeVuuVZ3SyBBasPf3SW6SzdQs',
    appId: '1:149592714644:web:ef1ed468afc4149d6a3381',
    messagingSenderId: '149592714644',
    projectId: 'chat-app-62edf',
    authDomain: 'chat-app-62edf.firebaseapp.com',
    storageBucket: 'chat-app-62edf.firebasestorage.app',
    measurementId: 'G-YKDXJZCVLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs2G1QrcmJRW_Zjf8SeefLmPZORFA1gQ0',
    appId: '1:149592714644:android:75c4467e480aea146a3381',
    messagingSenderId: '149592714644',
    projectId: 'chat-app-62edf',
    storageBucket: 'chat-app-62edf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn589zdG5Rd4jR7aYigqjMvg_ijiuaJkw',
    appId: '1:149592714644:ios:4dbfb8062867a27e6a3381',
    messagingSenderId: '149592714644',
    projectId: 'chat-app-62edf',
    storageBucket: 'chat-app-62edf.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn589zdG5Rd4jR7aYigqjMvg_ijiuaJkw',
    appId: '1:149592714644:ios:4dbfb8062867a27e6a3381',
    messagingSenderId: '149592714644',
    projectId: 'chat-app-62edf',
    storageBucket: 'chat-app-62edf.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMjUR6s_yeVuuVZ3SyBBasPf3SW6SzdQs',
    appId: '1:149592714644:web:20b5c1aedae0a7576a3381',
    messagingSenderId: '149592714644',
    projectId: 'chat-app-62edf',
    authDomain: 'chat-app-62edf.firebaseapp.com',
    storageBucket: 'chat-app-62edf.firebasestorage.app',
    measurementId: 'G-KGP8P39RXE',
  );
}
